/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_stanford_nlp_sempre_HunspellDictionary */

#ifndef _Included_edu_stanford_nlp_sempre_HunspellDictionary
#define _Included_edu_stanford_nlp_sempre_HunspellDictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_stanford_nlp_sempre_HunspellDictionary
 * Method:    nativeLoadLib
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_edu_stanford_nlp_sempre_HunspellDictionary_nativeLoadLib
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     edu_stanford_nlp_sempre_HunspellDictionary
 * Method:    nativeSpell
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_stanford_nlp_sempre_HunspellDictionary_nativeSpell
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     edu_stanford_nlp_sempre_HunspellDictionary
 * Method:    nativeSuggest
 * Signature: (JLjava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_edu_stanford_nlp_sempre_HunspellDictionary_nativeSuggest
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     edu_stanford_nlp_sempre_HunspellDictionary
 * Method:    nativeFreeLib
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_stanford_nlp_sempre_HunspellDictionary_nativeFreeLib
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
